version: "3.5"

volumes:
  prometheus_data: {}
  grafana_data: {}

services:
#  metrics-gateway:
#    image: prom/pushgateway
#    ports:
#      - 9091:9091

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
#      - 8080:8080
#    links:
#      - metrics-gateway:metrics-gateway
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus

  grafana-ui:
    image: grafana/grafana
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=secret
    # links:
    #   - prometheus-server:prometheus
    volumes:
      - grafana_data:/var/lib/grafana
